version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - DATABASE_URL=sqlite:///./data/database/robot_control.db
      - LOG_LEVEL=INFO
    depends_on:
      - db-init
    restart: unless-stopped

  db-init:
    build: .
    command: python -c "from app.core.database import init_db; init_db()"
    volumes:
      - ./data:/app/data
    environment:
      - DATABASE_URL=sqlite:///./data/database/robot_control.db

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./app/static:/usr/share/nginx/html:ro
    depends_on:
      - app
    restart: unless-stopped